Repository tomo-app/tomo_api, pull requests merged in 2021-02, with the labels that each got.

#69 Status optional get avail
  app/graphql/types/query_type.rb
  spec/queries/availability/get_availabilities_spec.rb
Labels: api, backend

#70 Add initial convo topics and translations to seed
  db/seeds.rb
Labels: backend, database

#71 Remove get all users query and refactor tests
  app/graphql/types/query_type.rb
  spec/mutations/availability/create_availability_spec.rb
  spec/mutations/availability/update_availability_spec.rb
  spec/mutations/user_language/create_user_language_spec.rb
  spec/mutations/users/create_user_spec.rb
  spec/queries/languages/get_languages_spec.rb
  spec/queries/users/get_user_spec.rb
  spec/queries/users/get_users_spec.rb
Labels: backend, testing

#68 Scheduling
  app/graphql/mutations/availabilities/create_availability.rb
  app/models/availability.rb
  app/models/pairing.rb
  app/models/user.rb
  spec/factories/user_languages.rb
  spec/models/availability_spec.rb
  spec/models/pairing_spec.rb
  spec/models/user_spec.rb
  spec/mutations/availability/create_availability_spec.rb
Labels: MVP, api, backend

#74 Blocked pairings
  app/graphql/mutations/blocked_pairings/create_blocked_pairing.rb
  app/graphql/types/blocked_pairing_type.rb
  app/graphql/types/input/blocked_pairing_input_type.rb
  app/graphql/types/mutation_type.rb
  app/models/user.rb
  spec/mutations/blocked_pairing/create_blocked_pairing_spec.rb
Labels: MVP, api, backend, blocked pairings

#79 Update availability
  app/graphql/mutations/availabilities/create_availability.rb
  app/graphql/mutations/availabilities/update_availability.rb
  spec/models/pairing_spec.rb
  spec/mutations/availability/update_availability_spec.rb
Labels: api, backend, testing

#84 Allow FE domain and local port 3000 to call API
  Gemfile
  Gemfile.lock
  config/initializers/cors.rb
  spec/factories/languages.rb
Labels: api, backend

#82 Add get random topic and its translations query
  README.md
  app/graphql/types/query_type.rb
  app/graphql/types/topic_translation_type.rb
  app/graphql/types/topic_type.rb
  app/models/topic.rb
  spec/factories/topic_translations.rb
  spec/factories/topics.rb
  spec/models/topic_spec.rb
  spec/queries/topic_translations/get_topic_and_translations_spec.rb
Labels: api, backend, topic_translations, topics

#91 Add test for createUser with mismatched password and confirmation
  app/graphql/mutations/users/create_user.rb
  spec/mutations/users/create_user_spec.rb
Labels: api, backend, testing

#83 Add cancelPairing mutation
  README.md
  app/graphql/mutations/pairings/cancel_pairing.rb
  app/graphql/types/mutation_type.rb
  app/models/availability.rb
  spec/mutations/pairings/cancel_pairing_spec.rb
Labels: api, backend, pairings

#92 Unique username/email
  app/graphql/mutations/users/create_user.rb
  spec/mutations/users/create_user_spec.rb
Labels: api, backend, testing

#94 Change fluency_level to input of integer instead of string
  README.md
  app/graphql/mutations/user_languages/create_user_language.rb
  app/graphql/mutations/users/create_user.rb
  app/graphql/types/input/user_language_input_type.rb
  spec/mutations/user_language/create_user_language_spec.rb
Labels: api, backend, refactor

#99 Fix bug for new availability for user without any user languages
  app/graphql/mutations/availabilities/create_availability.rb
  app/graphql/mutations/availabilities/update_availability.rb
  app/models/availability.rb
  spec/models/availability_spec.rb
  spec/mutations/availability/create_availability_spec.rb
Labels: api, backend, bug

#100 Don't allow for duplicate blocked pairings to be created
  app/graphql/mutations/blocked_pairings/create_blocked_pairing.rb
  app/models/blocked_pairing.rb
  spec/models/blocked_pairing_spec.rb
  spec/mutations/blocked_pairing/create_blocked_pairing_spec.rb
Labels: api, backend

#103 User cannot create duplicate user languages
  app/graphql/mutations/availabilities/create_availability.rb
  app/graphql/mutations/user_languages/create_user_language.rb
  spec/mutations/user_language/create_user_language_spec.rb
Labels: api, backend
